version: "3.8"

services:
  grobid:
    image: lfoppiano/grobid:0.7.2
    ports:
      - "8070:8070"
    restart: always

  analysis:
    build: .
    depends_on:
      - grobid
    environment:
      # Configura la URL de Grobid para que apunte al servicio "grobid"
      - GROBID_URL=http://grobid:8070
    volumes:
      - ./papers:/app/papers
      - ./output:/app/output
    restart: on-failure
